## array indexing 

In [1]:
import numpy as np

In [7]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[6]

np.int64(17)

## slice
#### index start from zero

In [9]:
arr[1:4]

array([12, 13, 14])

In [10]:
arr[ :5]

array([11, 12, 13, 14, 15])

## Numpy indexing and slicing of matrices

In [12]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [13]:
# if we wana print one(1) element of above matrix
arr[0,0]

np.int64(1)

In [17]:
# if we wana print 7 element of above matrix => (row,col)
arr[1,1]


np.int64(7)

In [20]:
##    slice now slice above matix [2,3],
##                                [7,8]
arr[0:2,1:3]


array([[2, 3],
       [7, 8]])

In [21]:
arr[0:2,3:]

array([[ 4,  5],
       [ 9, 10]])

### Boolen indexing
###### they give True false

In [24]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

#### Array operation 

In [29]:
#### Arithematic operation
a1 = np.array([1,2,3,4,5])
a2 = np.array([1,2,3,4,5])
a1,a2

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [30]:
a1 + a2

array([ 2,  4,  6,  8, 10])

In [31]:
#### they also multiple and so on
a1 * a2

array([ 1,  4,  9, 16, 25])

##### Brodcating 

In [36]:
l = [10,20,20,40]
arr = np.array([l])
arr + 10

array([[20, 30, 30, 50]])

### dot multiplication
###### matrics operation

In [37]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

A @ B

array([[19, 22],
       [43, 50]])

In [38]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [41]:
#### Transpose array
#### row become col

A . T

array([[1, 3],
       [2, 4]])

#### Advance array manipulations 

In [42]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
# horizantal join 2 array
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### spliting Array
#### split array into parts 

In [62]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### now play it 

In [61]:
c = np.split(c,2)
c

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [57]:
c = np.hsplit(c,2)
c

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [63]:
c = np.vsplit(c,2)
c

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# now is more search method and func and impove knowle