#basic array creation

In [122]:
import numpy as np

arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [123]:
#list
a = [1,2,3,4]
a

[1, 2, 3, 4]

# we can store multiple data types in list

In [124]:
a = [1,2,3,"hello",3.5]
a

[1, 2, 3, 'hello', 3.5]

In [125]:
# we can put multiple dataypes in array
# if we put a float value in then they convert integer to float bcas one of it in list

In [126]:
np.array(l)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# Now Vector and Matrices
# vector is 1D      
# Matrices is 2D
# list not support multi dimension but array does

In [127]:
l = [[1,2,3],[4,5,6],[7,8,9] ]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [128]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#  Normal Generation Function


In [129]:
# range fucntion

arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [130]:
# zeros func

arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [131]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [132]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# linear space / linspace 
# they give same space and generate number

In [133]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [134]:
arr = np.linspace(1,10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

# Random generation Function



In [135]:
 # We call Normalization Concept in stats
np.random.rand(10) 


array([0.21444224, 0.44248172, 0.96323199, 0.93899795, 0.02198963,
       0.70680705, 0.41325463, 0.38574776, 0.15951194, 0.00923403])

In [136]:
# standraization

arr = np.random.randn(10)
arr

array([-1.07138701,  0.81259869, -0.04366212, -0.79360265,  1.15141559,
       -1.54998186,  1.38807376, -3.02664071, -0.66466358,  0.12508671])

In [137]:
# random 

arr = np.random.randint(10,20,10)
arr

array([15, 14, 18, 16, 11, 12, 15, 11, 17, 16], dtype=int32)

# Array attributes 
 1.shape without brackets

In [138]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [139]:
arr.shape

(3, 3)

In [140]:
arr.size

9

In [141]:
arr.dtype

dtype('int64')

# Array Method

In [142]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
arr.min()

np.int64(1)

In [144]:
arr.max()

np.int64(9)

In [145]:
arr.sum()

np.int64(45)

In [146]:
# numpy func and its add verticaly
np.sum(arr,axis = 0)

array([12, 15, 18])

In [147]:
# horizintally
# addition row wise
np.sum(arr,axis = 1)


array([ 6, 15, 24])

In [148]:
arr.mean()


np.float64(5.0)

In [149]:
arr.std()

np.float64(2.581988897471611)

In [150]:
arr.argmax()

np.int64(8)

In [151]:
arr.argmin()

np.int64(0)

# reshaping and resizing 

In [152]:
arr= np.arange(1,31)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [153]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])